# Generated by Django 2.1.3 on 2018-11-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0002_auto_20181117_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Digits',
            new_name='Digit',
        ),
    ]
