# Generated by Django 2.1.3 on 2018-11-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0003_auto_20181117_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='bytes',
            field=models.TextField(default=None),
        ),
    ]
