# Generated by Django 2.1.3 on 2018-11-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0004_digit_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='digit1',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digit1', to='captcha.Digit'),
        ),
        migrations.AddField(
            model_name='captcha',
            name='digit2',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digit2', to='captcha.Digit'),
        ),
        migrations.AddField(
            model_name='captcha',
            name='digit3',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digit3', to='captcha.Digit'),
        ),
        migrations.AddField(
            model_name='captcha',
            name='digit4',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digit4', to='captcha.Digit'),
        ),
        migrations.AddField(
            model_name='captcha',
            name='digit5',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digit5', to='captcha.Digit'),
        ),
        migrations.AddField(
            model_name='captcha',
            name='digit6',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='digit6', to='captcha.Digit'),
        ),
    ]
