# Generated by Django 2.1.3 on 2018-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0006_auto_20181118_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='digit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/digits/'),
        ),
    ]
