# Generated by Django 2.1.3 on 2018-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0007_digit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='digits/'),
        ),
    ]
