# Generated by Django 2.1.3 on 2018-11-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0008_auto_20181118_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digit',
            name='path',
        ),
        migrations.AlterField(
            model_name='digit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
