# Generated by Django 2.1.3 on 2018-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0009_auto_20181118_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='value',
            field=models.SmallIntegerField(null=True),
        ),
    ]
