# Generated by Django 2.1.3 on 2018-11-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0012_auto_20181120_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='captcha',
            old_name='path',
            new_name='image',
        ),
    ]
