# Generated by Django 2.1.3 on 2018-11-21 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0014_auto_20181121_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='bytes',
            field=models.BinaryField(default=None),
        ),
    ]
