# Generated by Django 2.1.3 on 2018-11-21 00:35

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0015_auto_20181121_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='bytes',
            field=picklefield.fields.PickledObjectField(default=None, editable=False),
        ),
    ]
