# Generated by Django 2.1.3 on 2018-11-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0016_auto_20181121_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetwork',
            name='batch_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='epochs',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='test_set_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neuralnetwork',
            name='training_set_size',
            field=models.IntegerField(default=0),
        ),
    ]
