# Generated by Django 2.1.3 on 2018-11-21 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0017_auto_20181121_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuralnetwork',
            name='model_summary',
        ),
    ]
