# Generated by Django 2.1.3 on 2019-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0018_remove_neuralnetwork_model_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digit',
            name='value',
        ),
        migrations.AddField(
            model_name='digit',
            name='ascii_value',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
