# Generated by Django 2.1.3 on 2019-03-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0020_digit_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digit',
            name='value',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
