# Generated by Django 2.1.3 on 2019-03-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0021_auto_20190307_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralnetwork',
            name='confusion_matrix',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
