# Generated by Django 2.1.3 on 2019-03-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0022_neuralnetwork_confusion_matrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuralnetwork',
            name='confusion_matrix',
        ),
    ]
