# Generated by Django 2.1.3 on 2019-03-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0025_auto_20190315_1838'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NeuralNetworkEnsembles',
            new_name='Weight',
        ),
    ]
