# Generated by Django 2.1.3 on 2019-03-15 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0026_auto_20190315_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralNetworkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='weight',
            name='ensemble',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='neural_network',
        ),
        migrations.AlterField(
            model_name='ensemble',
            name='neural_networks',
            field=models.ManyToManyField(through='captcha.NeuralNetworkGroup', to='captcha.NeuralNetwork'),
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
        migrations.AddField(
            model_name='neuralnetworkgroup',
            name='ensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captcha.Ensemble'),
        ),
        migrations.AddField(
            model_name='neuralnetworkgroup',
            name='neural_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captcha.NeuralNetwork'),
        ),
    ]
