# Generated by Django 2.1.3 on 2019-03-16 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0027_auto_20190315_1924'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='neuralnetworkgroup',
            unique_together={('neural_network', 'ensemble')},
        ),
    ]
