# Generated by Django 2.2.1 on 2019-05-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0028_auto_20190316_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ensemble',
            name='accuracy',
            field=models.FloatField(null=True),
        ),
    ]
